---
- name: For Installing Packages On Remote Machines
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    -
      name: installing package
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "Redhat"
      tags: install apache
    - 
      name: Start the httpd
      service:
        name: httpd
        state: started
      when: ansible_os_family == "Redhat"  
      tags: start apache
    -
      name: Installing
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
      tags: install apache  
    - 
     name: Start the apache2
     service:
          name: apache2
          state: started
     when: ansible_os_family == "Debian"
     tags: start apache
    -
     name: Copying the index file
     copy: 
      src: /home/ansible/index.html
      dest: /var/www/html
      mode: 0666
