---
- name: For Installing Packages On Remote Machines
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    
    - 
      name: Stop the httpd
      service:
        name: httpd
        state: stopped
      when: ansible_os_family == "Redhat"
    -
      name: Removing package
      yum:
        name: httpd
        state: absent
      when: ansible_os_family == "Redhat"  
    - 
     name: Stop the apache2
     service:
          name: apache2
          state: stopped
     when: ansible_os_family == "Debian"
    -
      name: Removing package
      apt:
        name: apache2
        state: absent
      when: ansible_os_family == "Debian"